#!/usr/bin/env python3
"""Render contracts/EPILYKOS-OS-CONTRACTS.md from the YAML registry.

The registry (contracts/epilykos-os-contracts.yaml) is the source of truth.
Narrative sections live in contracts/narrative.md; the placeholders
{{INVARIANTS}}, {{CONTRACTS}}, {{ACCEPTANCE}}, {{DECISIONS}} and {{CHANGELOG}}
are replaced with tables/sections generated here, so the two can never drift.

Usage: render_contracts.py [--check]   (--check: exit 1 if the .md is stale)
"""
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / 'contracts' / 'epilykos-os-contracts.yaml'
NARRATIVE = ROOT / 'contracts' / 'narrative.md'
OUTPUT = ROOT / 'contracts' / 'EPILYKOS-OS-CONTRACTS.md'

LIST_SECTIONS = [
    ('requirements', 'Requirements'),
    ('baseline', 'Current baseline'),
    ('implementation_status', 'Implementation status'),
    ('unresolved', 'Unresolved before this contract can pass'),
    ('evidence', 'Required evidence'),
]


def cell(text):
    return str(text).replace('|', '\\|').replace('\n', ' ')


def invariants(reg):
    rows = ['| ID | Invariant | Verification |', '|---|---|---|']
    rows += [f"| `{i['id']}` | {cell(i['requirement'])} | {cell(i['verification'])} |" for i in reg['frozen_invariants']]
    return '\n'.join(rows)


def contracts(reg):
    out = []
    for c in reg['contracts']:
        out.append(f"### {c['id']} — {c['title']}\n")
        out.append(f"**Stage:** {c['stage']}  \n**Status:** `{c['status']}`\n")
        if c.get('rationale'):
            out.append(f"*Why:* {c['rationale']}\n")
        for key, title in LIST_SECTIONS:
            items = c.get(key)
            if items:
                out.append(f"**{title}**\n")
                out.extend(f"- {i}" for i in items)
                out.append('')
            if key == 'requirements' and c.get('manifest_schema'):
                out.append('**Canonical manifest shape**\n')
                out.append('```yaml')
                out.append(yaml.safe_dump(c['manifest_schema'], sort_keys=False, width=120).rstrip())
                out.append('```\n')
    return '\n'.join(out).rstrip()


def acceptance(reg):
    rows = ['| Test ID | Stage | Assertion |', '|---|---:|---|']
    tests = sorted(reg['acceptance_tests'], key=lambda t: (t['stage'], t['id']))
    rows += [f"| `{t['id']}` | {t['stage']} | {cell(t['assertion'])} |" for t in tests]
    return '\n'.join(rows)


def decisions(reg):
    rows = ['| Decision ID | Due stage | Status | Blocks | Question |', '|---|---:|---|---|---|']
    for d in reg['decisions_required']:
        blocks = ', '.join(f'`{b}`' for b in d['blocks'])
        rows.append(f"| `{d['id']}` | {d['due_stage']} | `{d['status']}` | {blocks} | {cell(d['question'])} |")
    return '\n'.join(rows)


def changelog(reg):
    out = []
    for entry in reg.get('changelog', []):
        out.append(f"### {entry['version']}\n")
        out.extend(f"- {c}" for c in entry['changes'])
        out.append('')
    return '\n'.join(out).rstrip()


def render():
    reg = yaml.safe_load(REGISTRY.read_text())
    text = NARRATIVE.read_text()
    meta = reg['metadata']
    for key, value in {
        '{{VERSION}}': meta['version'],
        '{{INVARIANTS}}': invariants(reg),
        '{{CONTRACTS}}': contracts(reg),
        '{{ACCEPTANCE}}': acceptance(reg),
        '{{DECISIONS}}': decisions(reg),
        '{{CHANGELOG}}': changelog(reg),
    }.items():
        text = text.replace(key, value)
    header = '<!-- GENERATED by tools/render_contracts.py from epilykos-os-contracts.yaml + narrative.md. Do not edit by hand. -->\n\n'
    return header + text.rstrip() + '\n'


def main():
    rendered = render()
    if '--check' in sys.argv:
        current = OUTPUT.read_text() if OUTPUT.exists() else ''
        if current != rendered:
            print('contracts/EPILYKOS-OS-CONTRACTS.md is stale: run `make render`', file=sys.stderr)
            return 1
        print('rendered document is up to date')
        return 0
    OUTPUT.write_text(rendered)
    print(f'wrote {OUTPUT.relative_to(ROOT)}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
